[project]
name = "freight-logistics-dashboard"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.11"
dependencies = [
    "plotly>=6.1.1",
    "streamlit>=1.45.1",
]
