[project]
name = "freight-logistics-dashboard"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.11"
dependencies = [
    "faker>=37.3.0",
    "mlflow>=2.22.0",
    "plotly>=6.1.1",
    "scikit-learn>=1.6.1",
    "streamlit>=1.45.1",
]
